### ISSUE TITLE
Big total package size

### ISSUE THREAD

**Issue by dsyme** [fable-compiler/fable-suave-scaffold#116]
The total package size download  is big - ~600MB under ``packages``

### Repro steps

Build and measure size of "packages" directory

### Expected behavior

Less package

### Actual behavior

Lotsa package

**Comment by dsyme** [comment]
Perhaps paket.dependencies could have 

    framework: auto-detect

Adding that seemed to reduce total package size to 400MB however the build then failed with 

![image](https://user-images.githubusercontent.com/7204669/27229548-e4fc5968-52a3-11e7-8ef6-35b453705a90.png)

**Comment by forki** [comment]
I think autodetect doesn't work with .NET SDK yet. @matthid or does it?

but even then: we have fable, .NET Core and .NET full projects so it would basically be "give me everything" again.

**Comment by matthid** [comment]
Yes, I did not touch that, but I still vote for getting rid of the packages folder :/

**Comment by forki** [comment]
You still have to download. And yes if someone would implement file links
that would be great

Am 17.06.2017 11:49 vorm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
For this particular issue it might make sense to first try and figure out what paket should not have downloaded and WHY. I cannot know because I still have not done much fable jet ;)

**Comment by alfonsogarciacaro** [comment]
Tell me about it, Fable "packages" folder is more than 1GB (half of it is the docs group) and I believe we don't have many dependencies ;)

Fable 1.x projects usually target netstandard so they should be able to share FSharp.Core with the server project (FSharp.Net.SDK will go away with dotnet sdk 2). Also Fable.XXX packages seem to take less than 10MB in total so I don't think the problem is there.

I guess having multiple groups make the size grow quickly as some things like FSharp.Core have to be downloaded multiple times. The System.XXX packages take around 350 MB (for the main group only), hopefully this also improves with dotnet sdk 2.

I'm all for reducing the size of the packages folder. I have a 256GB also with a Windows partition and I constantly have to delete cloned projects to make space. Having file links would be super nice, but I think Fable could also cope with the .nuget cache, as the location can be taken from the `.fsproj.nuget.g.props` as @enricosada pointed out, and the version of the packages from the `.fsproj.references` file.

**Comment by alfonsogarciacaro** [comment]
Related https://github.com/fsprojects/Paket/issues/2650

**Comment by alfonsogarciacaro** [comment]
Reopening, I'll update the repo so it uses new Paket `storage:none` feature :tada:

**Comment by alfonsogarciacaro** [comment]
With latest Fable version and Paket `storage:none`, the size of `packages` folder has been reduced to around 100MB :)
