### ISSUE TITLE
Getting lot of errors in chrome

### ISSUE THREAD

**Issue by detachmode** [fable-compiler/fable-suave-scaffold#154]
### Description

Just cloned the repo and run `./build.sh run`

<img width="1276" alt="bildschirmfoto 2017-09-02 um 23 11 23" src="https://user-images.githubusercontent.com/19249828/29998800-6216fe94-9034-11e7-8ae7-04af272443ff.png">

* Operating system: MacOS Siera
* Branch: master

**Comment by Mousaka** [comment]
Same here

**Comment by forki** [comment]
@alfonsogarciacaro ideas?

Am 03.09.2017 5:22 vorm. schrieb "Kristian Lundström" <
notifications@github.com>:

**Comment by detachmode** [comment]
OK got the answer from the fable chat.
I need to install the redux dev tools
https://github.com/zalmoxisus/redux-devtools-extension
or comment out
https://github.com/fable-compiler/fable-suave-scaffold/blob/f7b741d19fedd7c46ae1a3588e28e8d752a7db26/src/Client/App.fs#L168-L170

**Comment by detachmode** [comment]
Just getting one error when initially visiting the site.
<img width="754" alt="bildschirmfoto 2017-09-03 um 14 30 08" src="https://user-images.githubusercontent.com/19249828/30002885-73ace224-90b4-11e7-82ff-86b9fb45e0ee.png">

**Comment by alfonsogarciacaro** [comment]
Ups, we should mention about the redux dev tools in the README, sorry and thanks for checking @detachmode! 😅 

About the `Error parsing url` error. I think it's because the first time you load the page the hash part is empty, so parsing fails and just displays the default. I guess Elmish could handle URLs with empty hash without displaying the error (pinging @et1975), but it doesn't have practical consequences so we usually don't pay much attention to it :wink:

**Comment by detachmode** [comment]
I was playing around with this repo the last days and what I missed was some kind of Getting Started in the README.
It should address the topics:
* Adding a new page (it kind of borders me right now, that I need to touch so many functions and types to add my own, but i guess there is no better functional way doing that. As far as I see, other than going back to OOP and create a IPage interface)
*  Addressing the issue with chrome errors and that you can disable the debuging or install the Redu x Dev tools
* Adding new nuget package like FSharp.Data (that's what I am currently struggling with, because the server side is on dotnetcore 2.0 and Type Providers aren't supported, I guess)

**Comment by forki** [comment]
We're accepting pull requests for the documentation and in fact plan to
improve it soon. But please go ahead.

Regarding IPage - yes there are couple of places in elmish architecture
that needs touching. But all is driven by compiler warnings. An IPage is
definetly an alternative, but I personally see it inferior since in my apps
I have edge cases in every singles one of the places that are very easily
handled with our architecture and would be drama with OO. Yes there is some
boilerplate here if you only see the default case, but it's so nice if you
have to break out.

Am 04.09.2017 7:43 nachm. schrieb "detachmode" <notifications@github.com>:

**Comment by detachmode** [comment]
I will write a getting started section and create a pull request.
Maybe I will do it today evening.

**Comment by detachmode** [comment]
PR is out!

**Comment by et1975** [comment]
Elmish navigation parser falls through the `oneOf`entries until it finds a match, so you could create the entry that matches anything and add that at the end.
